server:
  port: 8006

spring:
  application:
    name: cloud-provider-user
  redis:
    # redis数据库索引（默认为0）
    database: 0
    # redis服务器地址（默认为localhost）
    host: 172.16.21.159
    # redis端口（默认为6379）
    port: 6379
    # redis访问密码（默认为空）
    password: admin@#$...
    # redis连接超时时间（单位为毫秒）
    timeout: 10000
    # redis连接池配置
    jedis:
      pool:
        # 最大可用连接数（默认为8，负数表示无限）
        max-active: 8
        # 最大空闲连接数（默认为8，负数表示无限）
        max-idle: 8
        # 最小空闲连接数（默认为0，该值只有为正数才有作用）
        min-idle: 0
        # 从连接池中获取连接最大等待时间（默认为-1，单位为毫秒，负数表示无限）
        max-wait: 60000