server:
  port: 9000

eureka:
  instance:
    hostname: localhost #eureka 服务端的实例名称
  client:
    # false 表示不向注册中心注册自己
    register-with-eureka: false
    #false 表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    feth-registry: false
    service-url:
      defaultZone: http://${erurka.instance.hostname}:${server.port}/eureka/